server:
  port: 9999
eureka:
  instance:
    hostname: cloud-config-service
  client:
#    false表示不向注册中心注册自己
    register-with-eureka: true
#    false表示自己端口为注册中心，并不需要检索服务
    fetch-registry: true
    service-url:
#      设置与Eureka Server交互的地址查询服务和注册服务器都需要依赖这个地址
#      defaultZone: http://eureka7002:7002/eureka/
       defaultZone: http://eureka7001:7001/eureka/
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangym-boy/spring-cloud-condig.git
          search-paths:
            - spring-cloud-condig
          skip-ssl-validation: true
      label: master
#rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
