server:
  port: 9527
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
#    false表示不向注册中心注册自己
    register-with-eureka: true
#    false表示自己端口为注册中心，并不需要检索服务
    fetch-registry: true
    service-url:
#      设置与Eureka Server交互的地址查询服务和注册服务器都需要依赖这个地址
#      defaultZone: http://eureka7002:7002/eureka/
       defaultZone: http://eureka7001:7001/eureka/
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心动态创建路由的功能
      routes:
        - id: payment_routh1 #路由ID，没有规则但要唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/getPaymentById/** #断言，路径相匹配的进行路由
#            - Host=**.baidu.com
#            - Method=Get
#            - Query=username
#            - After=2020-05-13T10:14:25.705+08:00[Asia/Shanghai]
#            - Before=2020-05-13T10:14:25.705+08:00[Asia/Shanghai]
#            - Between=2020-05-13T10:14:25.705+08:00[Asia/Shanghai],2020-05-14T10:14:25.705+08:00[Asia/Shanghai]
#            - Cookie=username,wym
#            - Header=X-Request-Id,

        - id: payment_routh2 #路由ID，没有规则但要唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由