server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/cloud?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: root
      password: zlj1012

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wym.pojo
eureka:
  instance:
    instance-id: payment8001
    prefer-ip-address: true
  client:
#      表示是否将自己注册进EurekaServer
    register-with-eureka: true
    #      是否从EurekaServer抓取自己的注册信息，单点无所谓，集群必须设置为true配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/

