server:
  port: 9001
spring:
  application:
    name: cloud-order-server
eureka:
  client:
    #      表示是否将自己注册进EurekaServer
    register-with-eureka: true
    #      是否从EurekaServer抓取自己的注册信息，单点无所谓，集群必须设置为true配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
ribbon:
#设置连接所用时间
  ReadTimeout: 5000
#设置从服务器读取可用资源所用时间
  ConnectTimeout: 5000
logging:
  level:
    com.wym.service.PaymentFeignService: debug
